// <auto-generated/>
// Copyright (c) ProPulse
// Constants for application-wide use.

namespace ProPulse.Core;

/// <summary>
/// Provides application-wide constant values for entity property constraints and configuration.
/// </summary>
public static class AppConstants
{
    /// <summary>
    /// The maximum length for entity ID properties (UUID string representation).
    /// </summary>
    public const int IdMaxLength = 36;

    /// <summary>
    /// The maximum length for article titles.
    /// </summary>
    public const int ArticleTitleMaxLength = 256;

    /// <summary>
    /// The maximum value for the $top (paging) parameter in list endpoints.
    /// </summary>
    public const int MaxTop = 100;

    /// <summary>
    /// The format used within the Timestamp series of headers.
    /// </summary>
    public const string TimestampFormat = "yyyy-MM-ddTHH:mm:ss.ffffffK";
}
